# MUST EDIT BELOW
sitename: Mein DDR-Leben
tagline: Ein Geschichtsrückblick.
url: http://mein-ddr-leben.de
ga: UA-XXXXX-X              #Google Analytics ID
# END
# CHOOSE YOUR PREFERENCE
pygments:    false
markdown:    maruku
permalink:   none
# END
exclude: LICENSE, README.markdown, Rakefile
