# MUST EDIT BELOW
sitename: Mein DDR-Leben
tagline: Cleverer Untertitel
url: http://mein-ddr-leben.de
ga: UA-XXXXX-X              #Google Analytics ID
sitemap: GOOGLEWEBMASTER    #Google webmaster verification code
# END
# CHOOSE YOUR PREFERENCE
pygments:    false
markdown:    maruku
permalink:   none
# END
exclude: LICENSE, README.markdown, Rakefile
